// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "sort_items.hpp"  // my header
#include "djinni_function_policies.hpp"
#include "item_list.hpp"
#include "sort_order.hpp"

namespace textsort {


void SortItems_djinni_binding::sort(::djinni::SharedPtr<textsort::SortItemsImpl> self, sort_order order, const ItemList & items) {
    auto _djinni_result = ::djinni::return_value_policy::Void<void>([&]() -> decltype(auto)
    {
        return self->sort(order, items);
    });
    return static_cast<void>(_djinni_result);
}

/*not-null*/ ::djinni::SharedPtr<SortItems> SortItems_djinni_binding::create_with_listener(const /*not-null*/ ::djinni::SharedPtr<TextboxListener> & listener) {
    auto _djinni_result = ::djinni::return_value_policy::Automatic</*not-null*/ ::djinni::SharedPtr<SortItems>>([&]() -> decltype(auto)
    {
        return std::make_shared<textsort::SortItemsImpl>(listener);
    
    });
    return static_cast</*not-null*/ ::djinni::SharedPtr<SortItems>>(_djinni_result);
}

ItemList SortItems_djinni_binding::run_sort(const ItemList & items) {
    auto _djinni_result = ::djinni::return_value_policy::Automatic<ItemList>([&]() -> decltype(auto)
    {
        return textsort::SortItemsImpl::run_sort(items);
    });
    return static_cast<ItemList>(_djinni_result);
}

} // namespace textsort
