// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_common.hpp"
#include "sort_items_impl.hpp"
#include <memory>

namespace textsort {

class TextboxListener;
enum class sort_order;
struct ItemList;

using SortItems = textsort::SortItemsImpl;

class SortItems_djinni_binding {
public:

    /** For the iOS / Android demo */
    static void sort(::djinni::SharedPtr<textsort::SortItemsImpl> self, sort_order order, const ItemList & items);

    static /*not-null*/ ::djinni::SharedPtr<SortItems> create_with_listener(const /*not-null*/ ::djinni::SharedPtr<TextboxListener> & listener);

    /** For the localhost / command-line demo */
    static ItemList run_sort(const ItemList & items);
};

} // namespace textsort
